### ISSUE TITLE
关于代码的问题

### ISSUE THREAD

**Issue by Dandelion111** [Keep-Passion/SESF-Fuse#1]
你好，我用你们的程序训练了一下，不知道为什么最后得出的loss曲线很乱，也没有收敛，而且lssim_loss一直是0，求助

**Comment by Keep-Passion** [comment]
你好，我查看了我的代码，在训练部分Lp误改成了L1范数，其实是用的L2范数，我已经修改了，这是我们的收敛曲线，目前可以收敛，Lssim的波动范围为0~1，Lp的波动范围比较大，建议分开可视化
