### ISSUE TITLE
请问一下如何用python实现NSST或者NSCT的图像融合

### ISSUE THREAD

**Issue by Dandelion111** [Keep-Passion/SESF-Fuse#2]
我想用NSST或者NSCT做图像融合，但始终找不到python相关的代码，请问前辈做过相关的研究吗？

**Comment by Keep-Passion** [comment]
我没有找到NSST代码，NSCT我找到刘宇博士的matlab代码：http://www.escience.cn/people/liuyu1/Codes.html，
在我的Experiment分支的image_fusion.py里面也有，我也没有找到过python代码，于是我目前采用的方式是python调用matlab引擎的形式实现实验对比

**Comment by Dandelion111** [comment]
好的，我找了好几天没有结果，还是要感谢您的帮助。

**Comment by NadiyaC249** [comment]
@Keep-Passion  你好 我找不到您说的image_fusion.py文件在哪里？麻烦你可以具体指一下吗

**Comment by Keep-Passion** [comment]
> 

Experiment分支
https://github.com/Keep-Passion/SESF-Fuse/blob/Experiment/image_fusion.py
