### ISSUE TITLE
更多图片的融合

### ISSUE THREAD

**Issue by seanXYZ** [Keep-Passion/SESF-Fuse#5]
多谢你的论文和代码~
我想请您研发更多图片的multi-focus image fusion(MFIF), 类似与基恩士VHX系列, 希望您感兴趣!

**Comment by Keep-Passion** [comment]
谢谢你，目前对于多张图像，我们只能逐个输入，逐个融合，后期我们会考虑多张图像融合的问题，能否把“基恩士VHX系列“的相关论文发给我？

**Comment by seanXYZ** [comment]
好啊，有空一起研究一下！ 周小勇 邮箱xiaoyong.zhou@bomming.com 签名由 网易邮箱大师 定制 在2020年06月02日 10:27，Keep-Passion 写道： 谢谢你，目前对于多张图像，我们只能逐个输入，逐个融合，后期我们会考虑多张图像融合的问题，能否把“基恩士VHX系列“的相关论文发给我？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by swjtulinxi** [comment]
你好，我在另一个densefuse上看到你用了他的代码，就想请问一下你知道他的训练输入数据集的格式吗
original_imgs_path = list_images('D:/Database/Image_fusion_MSCOCO/original/')--他这里只是输入了一个原图像文件夹，比如那个作者做的是可见光和红外，那么输入文件夹不是应该有两个吗，而且我看你的代码里也是只输入一个文件夹。。

还有一个比较重要的问题是，你的模型只是针对多聚焦图片吗，能否适用于其它类型的rgb图片呢

**Comment by Keep-Passion** [comment]
> 你好，我在另一个densefuse上看到你用了他的代码，就想请问一下你知道他的训练输入数据集的格式吗
> original_imgs_path = list_images('D:/Database/Image_fusion_MSCOCO/original/')--他这里只是输入了一个原图像文件夹，比如那个作者做的是可见光和红外，那么输入文件夹不是应该有两个吗，而且我看你的代码里也是只输入一个文件夹。。
> 
> 还有一个比较重要的问题是，你的模型只是针对多聚焦图片吗，能否适用于其它类型的rgb图片呢

你好，推荐你读一下DenseFuse或我们的工作SESFFuse的论文，这里面有个共同点，我们都将训练阶段和测试阶段分开，训练阶段是对单张图的重建，测试阶段才是两张图的融合，所以训练阶段只有一个文件夹。由于我们的github都提供了已经训练好的模型参数，你可以跳过训练阶段而直接使用。我们的方法SESF-Fuse里面用了空间频率滤波，这个在我们的文章中有讨论过其实更适用于多聚焦图像融合，而不适用于infraded-visible融合，多曝光图像融合需要考虑平滑程度，我们也并没有在这里增加。

**Comment by swjtulinxi** [comment]
好的，就是你们都用的自编码方法吧，还有你们都是用灰度图像训练的，是不是用灰度还是rgb对后面测试没影响，？，我的数据集是多模态的，就是分辨率相同，不同传感器的，就是一个rgb图像和一个代表物体高度的图像融合，不知道你的工作可不可以直接用啊

**Comment by Keep-Passion** [comment]
> 好的，就是你们都用的自编码方法吧，还有你们都是用灰度图像训练的，是不是用灰度还是rgb对后面测试没影响，？，我的数据集是多模态的，就是分辨率相同，不同传感器的，就是一个rgb图像和一个代表物体高度的图像融合，不知道你的工作可不可以直接用啊

DenseFuse方法用灰度图训练，推理时针对RGB图，将三个通道分别送入网络得到三个融合结果再合并为RGB，我们SESF-Fuse方法对于RGB图在测试时生成一个Decision Map【0~1】，然后根据Decision map在像素级与两原图相乘从而适用于RGB图。SESF-Fuse最关键的是这个决策图计算，如果你一个是RGB图像，另一个是灰度，可以考虑把RGB转成灰度后，让两张图计算决策图，再用这个决策图适用于你的多模态融合。期待你的工作

**Comment by swjtulinxi** [comment]
好的，感谢，那我是否还需要训练网络，还是可以直接用你的权重应用到我的数据上

**Comment by Keep-Passion** [comment]
> 好的，感谢，那我是否还需要训练网络，还是可以直接用你的权重应用到我的数据上

我建议是直接将权重应用到你的数据上先测试，如果效果不好，则考虑重新训练，如果效果依然不理想，请考虑其他改进方法。另外，由于这个issue是别人开启的，在这里回答你会骚扰到其他人，我关掉这个issue，如果你还有问题，再开一个issue吧

**Comment by mogu-shao** [comment]
您好，SESF怎么来实现多张图片融合（比如10张）？
