### ISSUE TITLE
你好，能提供一下"lp+lssim_se_sf_net_times30"文件吗？

### ISSUE THREAD

**Issue by wzzydezy** [Keep-Passion/SESF-Fuse#6]
运行时报错缺少"lp+lssim_se_sf_net_times30"文件，能提供一下吗？万分感谢！

**Comment by Keep-Passion** [comment]
你好，你看下你的文档目录nets->parameters->lp+lssim_se_sf_net_times30.pkl，查看下是否有，如果没有更新下读取目录，如果是我们代码问题，也请及时告诉我

**Comment by wzzydezy** [comment]
> 你好，你看下你的文档目录nets->parameters->lp+lssim_se_sf_net_times30.pkl，查看下是否有，如果没有更新下读取目录，如果是我们代码问题，也请及时告诉我

你好，找到了，谢谢，代码里面的是"lp+lssim_se_sf_net_times30"，加上文件名后缀就能正常运行了。

**Comment by Keep-Passion** [comment]
谢谢，我们之前更新完没注意到，我在我的代码中也修正
