### ISSUE TITLE
自己数据融合的效果

### ISSUE THREAD

**Issue by swjtulinxi** [Keep-Passion/SESF-Fuse#7]
![image](https://user-images.githubusercontent.com/50089266/85832533-df881f80-b7c2-11ea-8a24-807467f496d7.png)
你好，我直接用你的权重用到我的数据上，发现基本没有效果，那我应该重新训练吧，是不是一定要用coco数据集，用自己的数据集训练也可以吧，，另外我用densefuse还有点效果
![image](https://user-images.githubusercontent.com/50089266/85832662-16f6cc00-b7c3-11ea-961a-10a12c142dc1.png)

我主要是用那张灰度图弥补rgb图像光线暗和阴影的地方

**Comment by Keep-Passion** [comment]
看到你的图像，针对这个案例，我在我的论文中分析过，DenseFuse的L1Norm融合更适合与亮度差异比较大的图像融合，而SESF-Fuse的空间频率不适合，我认为DenseFuse比SESF-Fuse对你这个应用更加管用。其实如果你只是为了让灰度图中灰度值高的区域覆盖到RGB图中，我认为没必要用深度学习算法，那个灰度图可以简单的使用阈值法挑出来灰度值较高的区域，然后覆盖到RGB图中。

**Comment by swjtulinxi** [comment]
我是要把灰色图像信息融入rgb、中，灰色图代表地面地物高度，我这也是想让我的毕业论文多点内容多点新的地方

**Comment by Keep-Passion** [comment]
我个人觉得你的需求没有必要用到深度学习，可能用更好的展示方式能到达吸引人的效果：（1）热力图，用热力图以半透明遮罩形式覆盖RGB原图区域，颜色越深代表高度越高；（2）用三维可视化图，在三维上，用灰度图的灰度值代表RGB像素所在点的高度，理论上是可以重建个三维立体图的，你可以尝试下。这个作为本科毕设显示度高，但作为研究生毕设没有算法创新是不够的
